version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  build:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist

  unit_tests:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn test --maxWorkers 2

workflows:
  version: 2
  default:
    jobs:
      - install
      - build:
          requires:
            - install
      - unit_tests:
          requires:
            - install
