version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install --frozen-lockfile --no-progress
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint_src:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint:src

  lint_test:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint:test

  test:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:ci
      - store_test_results:
          path: reports/coverage/xunit.xml

  prepublish:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: .
      - run: yarn prepublishOnly

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint_src:
          requires:
            - install
      - lint_test:
          requires:
            - install
      - test:
          requires:
            - install
      - prepublish:
          requires:
            - install
